### ISSUE TITLE
Extra '@owner.save' not necessary

### ISSUE THREAD

**Issue by KristenLeach** [learn-co-curriculum/sinatra-complex-forms-associations#36]
In the 'post /owners' method of the ReadMe, I noticed an extra save added after the instance of owner has been persisted, and after running through Pry with a coach we found that it is not needed. 

post '/owners' do 
    @owner = Owner.create(params[:owner])
    if !params["pet"]["name"].empty?
      @owner.pets << Pet.create(name: params["pet"]["name"])
    end
    #binding.pry
    #@owner.save
    redirect "owners/#{@owner.id}"
  end

**Comment by DanielSeehausen** [comment]
Hi @KristenLeach! 

Thank you for bringing this to our attention. After reviewing the following block:
```ruby
post '/owners' do
  @owner = Owner.create(params[:owner])
  if !params["pet"]["name"].empty?
    @owner.pets << Pet.create(name: params["pet"]["name"])
  end
  @owner.save
  redirect to "owners/#{@owner.id}"
end
```
If I understand correctly, we do need to persist our `@owner` if our condition is hit! This is because the newly created pet has not yet been associated with the `@owner` when it is first created on the 2nd line above. While an owner can still be persisted without it, this reads to me that any new pet information passed in the creation form won't be until the 6th line. Please let me know if I am missing something here. Please keep in mind: `create` both instantiates the instance and persists in the database, whereas `save` just persists the current reality of the instance. 


--- 

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab.

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:

Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
Use Pry to poke around your Ruby (or Sinatra), Rails, or JavaScript code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
Use the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙

**Comment by KristenLeach** [comment]
Hello Daniel! 
Yes, this seems to make sense. So then why is it that the patch method does not require the extra save? I guess that is the part that throws me off! We are editing it and possibly adding new information to the owner, yet there isn’t the extra “@owner.save” listed in the patch route and it seemed to pass the tests fine. Does it make a difference when it is an edit vs. a new instance?

Thanks for responding!

Kristen
